<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductReplacedBy\Model;

use ProductReplacedBy\Model\Base\ProductReplacedBy as BaseProductReplacedBy;

/**
 * Class ProductReplacedBy
 * @package ProductReplacedBy\Model
 */
class ProductReplacedBy extends BaseProductReplacedBy
{
}
