<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductReplacedBy;

use Thelia\Module\BaseModule;
use Propel\Runtime\Connection\ConnectionInterface;
use Thelia\Install\Database;

/**
 * Class ProductReplacedBy
 * @package ProductReplacedBy
 */
class ProductReplacedBy extends BaseModule
{
    const MESSAGE_DOMAIN = "productreplacedby";
    const ROUTER = "router.productreplacedby";

    public function postActivation(ConnectionInterface $con = null)
    {
        $database = new Database($con);

        $database->insertSql(null, [__DIR__ . "/Config/create.sql", __DIR__ . "/Config/insert.sql"]);
    }
}
