<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductReplacedBy\Loop;

use ProductReplacedBy\Loop\Base\ProductReplacedBy as BaseProductReplacedByLoop;

/**
 * Class ProductReplacedBy
 * @package ProductReplacedBy\Loop
 */
class ProductReplacedBy extends BaseProductReplacedByLoop
{
    /**
     * You may now add your own logic
     */
}
