<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductReplacedBy\Loop\Base;

use Propel\Runtime\ActiveQuery\Criteria;
use Thelia\Core\Template\Element\BaseLoop;
use Thelia\Core\Template\Element\LoopResult;
use Thelia\Core\Template\Element\LoopResultRow;
use Thelia\Core\Template\Element\PropelSearchLoopInterface;
use Thelia\Core\Template\Loop\Argument\Argument;
use Thelia\Core\Template\Loop\Argument\ArgumentCollection;
use Thelia\Type\BooleanOrBothType;
use ProductReplacedBy\Model\ProductReplacedByQuery;

/**
 * Class ProductReplacedBy
 * @package ProductReplacedBy\Loop\Base
 * @author TheliaStudio
 */
class ProductReplacedBy extends BaseLoop implements PropelSearchLoopInterface
{

    /**
     * @param LoopResult $loopResult
     *
     * @return LoopResult
     */
    public function parseResults(LoopResult $loopResult)
    {
        /** @var \ProductReplacedBy\Model\ProductReplacedBy $entry */
        foreach ($loopResult->getResultDataCollection() as $entry) {
            $row = new LoopResultRow($entry);

            $row
                ->set("PRODUCT_ID", $entry->getProductId())
                ->set("REPLACED_BY_ID", $entry->getReplacedById())
            ;

            $this->addMoreResults($row, $entry);

            $loopResult->addRow($row);
        }

        return $loopResult;
    }

    /**
     * Definition of loop arguments
     *
     * example :
     *
     * public function getArgDefinitions()
     * {
     *  return new ArgumentCollection(
     *
     *       Argument::createIntListTypeArgument('id'),
     *           new Argument(
     *           'ref',
     *           new TypeCollection(
     *               new Type\AlphaNumStringListType()
     *           )
     *       ),
     *       Argument::createIntListTypeArgument('category'),
     *       Argument::createBooleanTypeArgument('new'),
     *       ...
     *   );
     * }
     *
     * @return \Thelia\Core\Template\Loop\Argument\ArgumentCollection
     */
    protected function getArgDefinitions()
    {
        return new ArgumentCollection(
            Argument::createIntListTypeArgument("product_id"),
            Argument::createIntListTypeArgument("replaced_by_id"),
            Argument::createEnumListTypeArgument(
                "order",
                [
                    "product_id",
                    "product_id-reverse",
                    "replaced_by_id",
                    "replaced_by_id-reverse",
                ],
                "product_id"
            )
        );
    }

    /**
     * this method returns a Propel ModelCriteria
     *
     * @return \Propel\Runtime\ActiveQuery\ModelCriteria
     */
    public function buildModelCriteria()
    {
        $query = new ProductReplacedByQuery();

        if (null !== $product_id = $this->getProductId()) {
            $query->filterByProductId($product_id);
        }

        if (null !== $replaced_by_id = $this->getReplacedById()) {
            $query->filterByReplacedById($replaced_by_id);
        }

        foreach ($this->getOrder() as $order) {
            switch ($order) {
                case "product_id":
                    $query->orderByProductId();
                    break;
                case "product_id-reverse":
                    $query->orderByProductId(Criteria::DESC);
                    break;
                case "replaced_by_id":
                    $query->orderByReplacedById();
                    break;
                case "replaced_by_id-reverse":
                    $query->orderByReplacedById(Criteria::DESC);
                    break;
            }
        }

        return $query;
    }

    protected function addMoreResults(LoopResultRow $row, $entryObject)
    {
    }
}
